### ISSUE TITLE
Precompling Error: `UndefVarError: PreallocatedLinearOperator`

### ISSUE THREAD

**Issue by Alalalalaki** [HighDimensionalEconLab/VarianceComponentsHDFE.jl#33] opened 2021-09-30 07:10 UTC
When I precompile the pkg, it raise `ERROR: LoadError: LoadError: UndefVarError: PreallocatedLinearOperator not defined`. I guess this have something to do with `function approxcholSolver(P::PreallocatedLinearOperator, la::AbstractArray; tol::Real=1e-6, maxits=300, verbose=0)` in solvers.jl?

Version info: 
<img src="https://user-images.githubusercontent.com/31154974/135404522-60505c71-ea2b-4d80-87cf-74fc8eaf0c80.png" style="zoom:20%">

**Comment by jlperla** [comment] 2021-09-30 16:16
@Alim-faraji can you take a look when you get a chance? Are thkngs working on Julia 1.6 to our knowledge?

@AlalalalakiJust to ensure that you did an `] instantiate` to have the latest versions

**Comment by Alim-faraji** [comment] 2021-09-30 18:04
It should work well on Julia 1.6.
I believe the error is due to inconsistencies with newer version of `LinearOperators.jl`. But it shouldn't be a problem if you don't update the packages. @Alalalalaki can you specify steps you take?

**Comment by jlperla** [comment] 2021-09-30 18:08
@Alim-faraji  we need a bound on that package in the project file if it isn't compatible with the newer versions?

**Comment by Alalalalaki** [comment] 2021-09-30 18:20
@Alim-faraji @jlperla In case I messed up my environment, I completely reinstalled the Julia1.6. And then I run `] dev https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl` and `] instantiate`. Again I get the same error.

**Comment by Alim-faraji** [comment] 2021-09-30 18:25
> @Alim-faraji we need a bound on that package in the project file if it isn't compatible with the newer versions?

@jlperla I'm still not sure the issue is with the package inconsistencies. I look into that.

**Comment by Alim-faraji** [comment] 2021-09-30 19:28
@Alalalalaki Try again. There shouldn't be any problems anymore.

**Comment by Alalalalaki** [comment] 2021-09-30 19:56
@Alim-faraji Yes it works now.

**Comment by Alim-faraji** [comment] 2021-09-30 20:00
I'm closing this issue.

**Closed as completed by Alim-faraji** 2021-09-30 20:00 UTC
